default: &default
  adapter: <%= ENV['DATABASE_ADAPTER'] %>
  encoding: utf8
  reconnect: false
  pool: 5
  secure_auth: false
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default

production:
  <<: *default